version: "3.7"

services:
  database:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: "apice"
    ports:
      - 5432:5432